[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "handcalcs"
authors = [{name = "Connor Ferster", email = "connorferster@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: Apache Software License"]
dynamic = ["version", "description"]
dependencies = [
    "more_itertools",
    "nbconvert >= 6.0",
    "innerscope >= 0.7.0",
    "pyparsing"
]

[project.urls]
Source = "https://github.com/connorferster/handcalcs"


[project.optional-dependencies]

test = [
    "pytest >= 6.0.0",
    "pytest-cov >= 2.9.0",
    "coverage[toml] >= 5.5.0",
    "pint >= 0.18",
]

dev = [
    "jupyterlab >= 4.0.0",
    "sympy",
    "forallpeople >= 2.0",
    "black"  
]

doc = ["sphinx"]

[project.entry-points."nbconvert.exporters"]
HTML_NoInput = 'handcalcs.exporters:HTMLHideInputExporter'
PDF_NoInput = 'handcalcs.exporters:PDFHideInputExporter'
LaTeX_NoInput = 'handcalcs.exporters:LatexHideInputExporter'

[tool.coverage.paths]
source = ['handcalcs', '*/site-packages']

[tool.coverage.run]
branch = true
source = ['handcalcs']

[tool.coverage.report]
show_missing = true